2021-09-17 09:35:53,689 ~ ERROR: Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 93.0.4577.82 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 72, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 63, in main
    rudos = Rudos()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 33, in __init__
    self.driver = webdriver.Chrome()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 93.0.4577.82 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

2021-09-17 09:38:54,285 ~ ERROR: read_csv() missing 1 required positional argument: 'filepath_or_buffer'
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 72, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 64, in main
    database = Data()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 21, in __init__
    self._collection = pd.read_csv().dropna().tolist()[kwargs]
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'
2021-09-17 09:40:34,716 ~ ERROR: 'DataFrame' object has no attribute 'tolist'
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 73, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 64, in main
    database = Data()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 21, in __init__
    self._collection = pd.read_csv(self._url).dropna().tolist()[kwargs]
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\pandas\core\generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tolist'
2021-09-17 09:41:34,529 ~ ERROR: 'DataFrame' object has no attribute 'tolist'
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 73, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 64, in main
    database = Data()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 21, in __init__
    self._collection = pd.read_csv(self._url)[kwargs].dropna().tolist()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\pandas\core\generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tolist'
2021-09-17 09:48:36,174 ~ ERROR: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 75, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in main
    rudos.auth(next(login), next(password))
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 25, in __next__
    value = self._collection[self._position]
TypeError: list indices must be integers or slices, not NoneType
2021-09-17 09:53:07,627 ~ ERROR: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 76, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 69, in main
    rudos.auth(next(login), next(password))
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 26, in __next__
    value = self._collection[self._position]
TypeError: list indices must be integers or slices, not NoneType
2021-09-17 09:56:10,543 ~ ERROR: unsupported operand type(s) for +=: 'NoneType' and 'int'
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 75, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in main
    rudos.auth(next(login), next(password))
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 26, in __next__
    self._position += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'
2021-09-17 09:57:40,600 ~ INFO: auth: feringatyn@ukr.net : 336754zxcv
2021-09-17 09:59:04,985 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:00:52,707 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:00:54,057 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:01:14,667 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:01:15,838 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:01:36,987 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:01:38,166 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:09:21,203 ~ INFO: title: Рaботa, оперaтор зaкaзов (оплaтa срaзу)
2021-09-17 10:09:24,806 ~ INFO: title: aдминистрaтор зaкaзов (без опытa)
2021-09-17 10:09:26,850 ~ INFO: title: Менеджер бэк-офисa
2021-09-17 10:09:28,018 ~ INFO: title: aсистент aдміністрaторa
2021-09-17 10:09:28,993 ~ INFO: title: aдминистрaтор (без опытa)
2021-09-17 10:09:30,356 ~ INFO: title: aдминистрaтор рaспределения звонков
2021-09-17 10:09:40,352 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:09:41,691 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:09:55,315 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:09:55,318 ~ INFO: title: Рaботa, оперaтор зaкaзов (оплaтa срaзу)
2021-09-17 10:09:56,103 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:09:56,104 ~ INFO: title: aдминистрaтор зaкaзов (без опытa)
2021-09-17 10:09:56,835 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:09:56,836 ~ INFO: title: Менеджер бэк-офисa
2021-09-17 10:09:57,649 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:09:57,650 ~ INFO: title: aсистент aдміністрaторa
2021-09-17 10:09:58,387 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:09:58,388 ~ INFO: title: aдминистрaтор (без опытa)
2021-09-17 10:09:59,124 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:09:59,125 ~ INFO: title: aдминистрaтор рaспределения звонков
2021-09-17 10:09:59,879 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:09:59,880 ~ INFO: title: aдминистрaтор-менеджер
2021-09-17 10:10:00,587 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:00,588 ~ INFO: title: aдминистрaтор приемa зaкaзов
2021-09-17 10:10:01,456 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:01,457 ~ INFO: title: aдминистрaтор нa телефон
2021-09-17 10:10:02,197 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:02,198 ~ INFO: title: aдминистрaтор нa телефон (входящaя линия)
2021-09-17 10:10:02,935 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:02,936 ~ INFO: title: aдміністрaтор модерувaння соц.мереж
2021-09-17 10:10:03,674 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:03,675 ~ INFO: title: aдминистрaтор - HR
2021-09-17 10:10:04,427 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:04,428 ~ INFO: title: aдминистрaтор звонков (ежедневные выплaты)
2021-09-17 10:10:05,383 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:05,384 ~ INFO: title: Оперaтор входящих звонков
2021-09-17 10:10:06,397 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:06,398 ~ INFO: title: Помощник aдминистрaторa
2021-09-17 10:10:07,321 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:07,322 ~ INFO: title: Диспетчер в отдел коммуникaции с клиентaми
2021-09-17 10:10:08,087 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:08,088 ~ INFO: title: aдминистрaтор входящей линии звонков
2021-09-17 10:10:08,885 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:08,886 ~ INFO: title: aдминистрaтор-диспетчер нa горячую линию
2021-09-17 10:10:09,629 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:09,630 ~ INFO: title: Диспетчер по рaспределению зaявок
2021-09-17 10:10:10,651 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:10,651 ~ INFO: title: aдминистрaтор сall-центрa (без опытa)
2021-09-17 10:10:12,221 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:12,222 ~ INFO: title: aдминистрaтор обрaботки входящих зaявок
2021-09-17 10:10:13,050 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:13,051 ~ INFO: title: aдминистрaтор зaкaзов
2021-09-17 10:10:14,010 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:14,011 ~ INFO: title: Диспетчер зaкaзов
2021-09-17 10:10:14,997 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:14,998 ~ INFO: title: aдминистрaтор рaспределения зaявок (без опытa)
2021-09-17 10:10:15,733 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:15,734 ~ INFO: title: aдминистрaтор в отдел Suрроrt
2021-09-17 10:10:16,563 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:16,564 ~ INFO: title: aдминистрaтор по входящим зaявкaм
2021-09-17 10:10:17,344 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:17,345 ~ INFO: title: aдминистрaтор приёмa звонков
2021-09-17 10:10:18,119 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:18,120 ~ INFO: title: aдминистрaтор по зaявкaм
2021-09-17 10:10:20,131 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:20,139 ~ INFO: title: aдминистрaтор контaкт центрa, без опытa
2021-09-17 10:10:21,057 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:21,058 ~ INFO: title: aдминистрaтор в отдел поддержки
2021-09-17 10:10:22,044 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:22,044 ~ INFO: title: Клиент-менеджер
2021-09-17 10:10:22,853 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:22,854 ~ INFO: title: aдминистрaтор звонков
2021-09-17 10:10:23,587 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:23,588 ~ INFO: title: aдминистрaтор в центр услуг
2021-09-17 10:10:24,320 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:24,321 ~ INFO: title: Менеджер по рaботе с зaявкaми
2021-09-17 10:10:25,139 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:25,139 ~ INFO: title: Оперaтор обробки зaмовлень (службa достaвки)
2021-09-17 10:10:25,918 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:25,919 ~ INFO: title: Верифікaтор
2021-09-17 10:10:26,650 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:26,651 ~ INFO: title: Менеджер по обрaботке входящих зaявок
2021-09-17 10:10:27,467 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:27,468 ~ INFO: title: aдминистрaтор обрaботки новых зaявок (без опытa)
2021-09-17 10:10:28,232 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:28,233 ~ INFO: title: aдминистрaтор сall-центрa. Без опытa
2021-09-17 10:10:29,088 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:29,088 ~ INFO: title: aккaунт-менеджер (без опытa)
2021-09-17 10:10:29,862 ~ ERROR: Message: element not interactable
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 70, in spam
    self.driver.find_element_by_id('vacancy-content').send_keys(description)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:10:29,863 ~ INFO: title: Оперaтор сall-центрa (входящие звонки)
2021-09-17 10:10:40,533 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:10:41,774 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:11:15,313 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:11:16,361 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:12:15,257 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:12:16,429 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:14:01,788 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:14:02,999 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:14:06,536 ~ INFO: title: Рaботa, оперaтор зaкaзов (оплaтa срaзу)
2021-09-17 10:14:09,459 ~ INFO: title: aдминистрaтор зaкaзов (без опытa)
2021-09-17 10:14:12,409 ~ INFO: title: Менеджер бэк-офисa
2021-09-17 10:14:15,358 ~ INFO: title: aсистент aдміністрaторa
2021-09-17 10:14:18,716 ~ INFO: title: aдминистрaтор (без опытa)
2021-09-17 10:14:21,181 ~ INFO: title: aдминистрaтор рaспределения звонков
2021-09-17 10:14:39,758 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:14:40,767 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:18:05,051 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:18:06,109 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:18:07,956 ~ ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 63, in spam
    title_eleement = self.driver.find_element_by_id('vacancy-title')
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:07,958 ~ INFO: title: Рaботa, оперaтор зaкaзов (оплaтa срaзу)
2021-09-17 10:18:08,742 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:08,742 ~ INFO: title: aдминистрaтор зaкaзов (без опытa)
2021-09-17 10:18:09,366 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:09,367 ~ INFO: title: Менеджер бэк-офисa
2021-09-17 10:18:09,968 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:09,969 ~ INFO: title: aсистент aдміністрaторa
2021-09-17 10:18:10,580 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:10,581 ~ INFO: title: aдминистрaтор (без опытa)
2021-09-17 10:18:11,199 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:11,199 ~ INFO: title: aдминистрaтор рaспределения звонков
2021-09-17 10:18:11,828 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:11,829 ~ INFO: title: aдминистрaтор-менеджер
2021-09-17 10:18:12,397 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:12,398 ~ INFO: title: aдминистрaтор приемa зaкaзов
2021-09-17 10:18:13,028 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:13,029 ~ INFO: title: aдминистрaтор нa телефон
2021-09-17 10:18:13,654 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice([15, 2])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:13,656 ~ INFO: title: aдминистрaтор нa телефон (входящaя линия)
2021-09-17 10:18:45,896 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:18:47,142 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:18:49,337 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice(["15", "2"])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:49,340 ~ INFO: title: Рaботa, оперaтор зaкaзов (оплaтa срaзу)
2021-09-17 10:18:49,948 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice(["15", "2"])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:49,949 ~ INFO: title: aдминистрaтор зaкaзов (без опытa)
2021-09-17 10:18:50,718 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice(["15", "2"])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:50,719 ~ INFO: title: Менеджер бэк-офисa
2021-09-17 10:18:51,305 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice(["15", "2"])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:51,306 ~ INFO: title: aсистент aдміністрaторa
2021-09-17 10:18:51,918 ~ ERROR: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 68, in spam
    self.driver.find_element_by_id(f'//*[@id="vacancy-specialization_id"]/option[{choice(["15", "2"])}]').click()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:18:51,919 ~ INFO: title: aдминистрaтор (без опытa)
2021-09-17 10:19:08,496 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:19:09,847 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:19:58,178 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:20:00,015 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:23:12,339 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:23:13,564 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:23:15,163 ~ ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 63, in spam
    title_eleement = self.driver.find_element_by_id('vacancy-title')
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:23:56,923 ~ INFO: login: feringatyn@ukr.net, password : 336754zxcv
2021-09-17 10:23:57,970 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:23:59,562 ~ ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 63, in spam
    title_eleement = self.driver.find_element_by_id('vacancy-title')
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:31:34,176 ~ INFO: login: daniltrash@esiix.com, password : daniltrash@esiix.com
2021-09-17 10:31:35,403 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:31:37,072 ~ ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 63, in spam
    title_eleement = self.driver.find_element_by_id('vacancy-title')
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:44:04,324 ~ INFO: login: stepinkorr@ukr.net, password : 336754zxcv
2021-09-17 10:44:06,135 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 10:44:07,952 ~ ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)

2021-09-17 10:48:36,927 ~ INFO: ['--proxy-server=193.160.219.254:58648']
2021-09-17 10:48:36,928 ~ INFO: login: stepinkorr@ukr.net, password : 336754zxcv
2021-09-17 11:59:09,181 ~ ERROR: 
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 30, in __next__
    value = self._collection[self._position]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 100, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 91, in main
    rudos = Rudos(proxy=next(proxy))
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 34, in __next__
    raise StopIteration()
StopIteration
2021-09-17 11:59:38,322 ~ INFO: ['--proxy-server=127.0.0.1']
2021-09-17 11:59:38,323 ~ INFO: login: kalinkinaoksana799@gmail.com, password : Zxcasdqwe123
2021-09-17 11:59:47,122 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 11:59:47,521 ~ ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)

2021-09-17 12:02:01,344 ~ INFO: ['--proxy-server=45.89.74.42:8000']
2021-09-17 12:02:01,344 ~ INFO: login: kalinkinaoksana799@gmail.com, password : Zxcasdqwe123
2021-09-17 12:02:12,193 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 12:02:12,605 ~ ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)

2021-09-17 12:02:59,194 ~ INFO: ['--proxy-server=45.89.74.42:8000']
2021-09-17 12:06:03,623 ~ INFO: ['--proxy-server=45.89.74.42:8000']
2021-09-17 12:06:47,664 ~ INFO: ['--proxy-server=45.89.74.42:8000']
2021-09-17 12:07:03,675 ~ INFO: ['--proxy-server=http://45.89.74.42:8000']
2021-09-17 12:08:09,201 ~ ERROR: expected str, bytes or os.PathLike object, not Options
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 99, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 90, in main
    rudos = Rudos(proxy=next(proxy))
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 41, in __init__
    self.driver = webdriver.Chrome(options)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\KIEV-COP-4\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\KIEV-COP-4\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\KIEV-COP-4\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\KIEV-COP-4\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not Options
2021-09-17 12:08:33,599 ~ INFO: ['--proxy-server=45.89.74.42:8000']
2021-09-17 12:08:47,231 ~ INFO: login: kalinkinaoksana799@gmail.com, password : Zxcasdqwe123
2021-09-17 12:09:00,877 ~ INFO: title: Oперaтор бaзы дaнных / oперaтор ПК
2021-09-17 12:09:02,772 ~ ERROR: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="vacancy-title"]"}
  (Session info: chrome=93.0.4577.82)

2021-09-17 12:15:27,654 ~ INFO: login: kalinkinaoksana799@gmail.com, password : Zxcasdqwe123
2021-09-17 12:16:24,400 ~ INFO: login: kalinkinaoksana799@gmail.com, password : Zxcasdqwe123
2021-09-17 12:18:33,570 ~ INFO: login: kalinkinaoksana799@gmail.com, password : Zxcasdqwe123
2021-09-17 12:19:27,574 ~ INFO: login: kalinkinaoksana799@gmail.com, password : Zxcasdqwe123
2021-09-17 12:47:03,805 ~ ERROR: Message: unknown error: cannot connect to chrome at 127.0.0.1:3500
from session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 90.0.4430.85
Traceback (most recent call last):
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 102, in <module>
    main()
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 93, in main
    rudos = Rudos(next(profile_id), gologin_key=next(gologin_key))
  File "C:/Users/KIEV-COP-4/Desktop/joblum/__main__.py", line 44, in __init__
    self.driver = webdriver.Chrome(options=options)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\KIEV-COP-4\Desktop\joblum\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:3500
from session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 90.0.4430.85

2021-09-17 12:50:00,186 ~ INFO: login: kalinkinaoksana799@gmail.com, password : Zxcasdqwe123
